### ISSUE TITLE
Znode Tool Window Bar shows v1.0.1

### ISSUE THREAD

**Issue by jTd7bPLFb** [zcoinofficial/znode-tool-evo#12]

**Comment by jTd7bPLFb** [comment]
![Screen Shot 2021-04-23 at 10 05 45](https://user-images.githubusercontent.com/71418817/115891416-adb00b80-a41b-11eb-9a72-7b5f0970ae6f.jpg)

**Comment by a-bezrukov** [comment]
Fixed
