### ISSUE TITLE
Provide .desktop file for linux

### ISSUE THREAD

**Issue by yura-pakhuchiy** [zcoinofficial/znode-tool-evo#6]
`flatpak run  io.zcoin.ZnodeTool` is not very user friendly way to launch. Please add  `.desktop` file to flatpak, so that the tool can be launched via click on icon.

**Comment by yura-pakhuchiy** [comment]
You might find this comment useful: https://github.com/flatpak/flatpak/issues/1286#issuecomment-354554684

**Comment by a-bezrukov** [comment]
Fixed, please download the 1.0.3 release
